### ISSUE TITLE
Unpublished tutorials are still indexed

### ISSUE THREAD

**Issue by michaelhagedon** [ualibraries/Guide-on-the-Side#109]

**Comment by michaelhagedon** [comment]
I noticed this when unpublishing an already-published tutorial.

**Comment by simpsonw** [comment]
I believe I have fixed this.  My changes are in the 569_lucene_bug branch.

**Comment by michaelhagedon** [comment]
Looks good to me! Thanks.

**Comment by simpsonw** [comment]
No problem, @michaelhagedon!  Does this mean I should merge 569_lucene_bug into master?

**Comment by michaelhagedon** [comment]
Seems OK to me.

**Comment by simpsonw** [comment]
The branch has been merged, so I'm closing this issue.
