### ISSUE TITLE
"Next" and "Previous" show up out of place on long tutorials

### ISSUE THREAD

**Issue by simpsonw** [ualibraries/Guide-on-the-Side#136]
# Steps to reproduce
1. Create a tutorial with lots (> 40) of chapters/page breaks.
2. Scroll through the tutorial.
# Expected result

Only the arrow navigation will show below the content.
# Actual result

The "Previous" and "Next" text partially displays:

![gots_prev_next_bug](https://cloud.githubusercontent.com/assets/10437788/9696688/f23e16b4-5329-11e5-99b8-866955b58ba7.png)
# Notes

It appears that the text is coming from a "step" div that has not yet been navigated to and is some how wrapping around.  Decreasing the width on the .items form seems to help, but I'm not sure if that has any weird side effects.

**Comment by caosborne89** [comment]
I think this has to do with how the height for each "scrollable" container is being set. One way to get a better look is to uncheck overflow-x  for div#scrollable and scroll a little to the right. It almost looks what's being cutoff from the other steps is leaking into the current step. Take a look at app/webroot/js/tutorials/view_tutorial_only.jsview_tutorial_only.js

**Comment by caosborne89** [comment]
So I've committed the only fix that I could come up with. It seems to work correctly, though I'd really appreciate it if someone could review this before merging. I'm not sure why we needed the inner html (Next and Previous) in the first place, so I maybe overlooking something.

**Comment by zensense** [comment]
This seems to work where we leave an empty string for the title parameter of HTML->link() signature. I feel this is a bit hacky, but maybe necessary due to Cake internals for templates. https://book.cakephp.org/2.0/en/core-libraries/helpers/html.html

@caosborne89 Can you check your code and make sure that you only leave the title parameter empty.
