### ISSUE TITLE
PHP Notice:  Use of undefined constant username - assumed 'username' in CasAuthenticate.php on line 59 

### ISSUE THREAD

**Issue by pbhenson** [ualibraries/Guide-on-the-Side#177]
Looks like there's a missing $ in the code in question:

    public function getUser($request = null) {
        $username = $this->determineUsername();
        if (username) {
            return $this->_findUser($username);
        } else {
            return false;
        }
    }

**Comment by michaelhagedon** [comment]
Thanks, @pbhenson! I don't have CAS set up to test this right now, but that's a obvious error. This is fixed in `master`; let us know if you find it doesn't work.
