### ISSUE TITLE
PHP 7 Version

### ISSUE THREAD

**Issue by vbielat** [ualibraries/Guide-on-the-Side#179]
Apolgies for my very novice question.
I have been told by our tech guru we can't have Guide on the Side because there is not a PHP7 version (only PHP5). This has something to do with the need to run a PHP7 server only.

I see there are some PHP7 entries in the Code, but cannot understand what it is saying. 

Is there a PHP7 version or code updates and how can I point our tech guru to them so this can be installed.

Thank you.

**Comment by caosborne89** [comment]
Hello vbielat,
The current master branch has php7 support. The master branch is ahead of our current release. So I would just let your techies know to grab the git repository and use the master branch. Let me know if you have any other questions

Thanks,
Andy

**Comment by vbielat** [comment]
Thank you so much for your super fast response!! I can leave for the weekend with my to-do list done!  Have a great holiday.

Veronica

**Comment by michaelhagedon** [comment]
We'll do more work specifically around 7.2 in #181 .
