### ISSUE TITLE
Make search engines find the actual tutorial and not view_tutorial_only

### ISSUE THREAD

**Issue by michaelhagedon** [ualibraries/Guide-on-the-Side#47]
Google indexes the tutorial frame, not the tutorial itself. Makes sense from Google's perspective, but confusing for users.

**Comment by simpsonw** [comment]
Is this still an issue?  I was looking into it, so I searched for "Searching Academic Search Complete" in Google.  The first result took me to http://www.library.arizona.edu/applications/quickHelp/tutorial/searching-academic-search-complete.  Is that not the correct behavior?

**Comment by michaelhagedon** [comment]
That's correct. Maybe we fixed it already? Or the search engines are getting smarter?


Sent from a mobile device


-------- Original message --------

**Comment by simpsonw** [comment]
Given that it seems to be working, I'm going to close this.  If we run into problems in the future, we can create a new issue.
