### ISSUE TITLE
LexisNexis Academic Loses Functionality inside of Guide on the Side

### ISSUE THREAD

**Issue by bgalbreath** [ualibraries/Guide-on-the-Side#65]
Hello,

We have recently created a GOTS highlighting LexisNexis Academic. However, LNA doesn't not seem to function inside of GOTS. (It works perfectly fine outside of GOTS.) In this tutorial, we navigate to LNA from library.eou.edu. The LNA landing page displays normally, but any links or searches from there just seem to loop back to the LNA landing page. Similar tutorials with other databases are working fine.

LNA upgraded last month. I suspect that there is some kind of conflict, but not sure where to start. I did call LNA - they are stumped as well.

This behavior seems very similar to #23, but I created new thread since it is a different vendor/database.

Any help would be appreciated - thanks.

**Comment by michaelhagedon** [comment]
Strangely, this is working without pop-up mode (#50) in Firefox 34, but in Chrome 39 I get "Your browser must have cookies enabled to use this site. Consult your browser's Help section to enable cookies." from LNA. IE 11 is also working. The only solution may be using pop-up mode, but we'll see.

**Comment by simpsonw** [comment]
Just tried this without pop-up mode in Chrome 40.0.2214.94 and it seemed to work fine for me.

**Comment by michaelhagedon** [comment]
Yeah, I think their interface changed, so this issue is probably invalid.

**Comment by simpsonw** [comment]
Okay, I am going to close this for now, if people experience problems in the future we can create a new issue.
