### ISSUE TITLE
GotS email never gets delivered to gmail

### ISSUE THREAD

**Issue by michaelhagedon** [ualibraries/Guide-on-the-Side#72]
At least from what I've seen...

**Comment by jaronkk** [comment]
I've been able to receive emails from GotS in both my personal gmail and my work (Notre Dame) gmail account.

Could it be that Gmail is marking email sent by your web server as spam, rather than specifically GotS?

**Comment by simpsonw** [comment]
Gmail seems to at least work with the SMTP option from #106.  Any objections to me closing this task?

**Comment by michaelhagedon** [comment]
Go for it.

**Comment by simpsonw** [comment]
Closed by #106.
