### ISSUE TITLE
Improve affordance for definition boxes

### ISSUE THREAD

**Issue by liquid06** [ualibraries/Guide-on-the-Side#90]
It's not clear that definition boxes are things you can interact with. Some ideas we've discussed for resolving this:
* Adding +/- or X icons
* Making them look like regular links

**Comment by FStop** [comment]
Where can one find an example of this?

**Comment by michaelhagedon** [comment]
It might be mainly that the dotted underline on the links confused students, but I'm not sure. @simpsonw may have addressed this here: 2cc03cece83a793f41172c8548554d5855a3637c

**Comment by simpsonw** [comment]
That's correct, @michaelhagedon, it was a simple change to make the bottom solid so they look like "normal" links, although I'm certainly open to any other suggestions.

**Comment by michaelhagedon** [comment]
Oh, and as far as an example, the "Keyword search" thing on the first slide here is a definition box:
http://www.library.arizona.edu/applications/quickHelp/tutorial/locating-childrens-literature

**Comment by simpsonw** [comment]
I deployed the changes from #92 to http://webdev.library.arizona.edu/applications/quickHelp/tutorial/1-visited-link-colors-and-definition-boxes-test.  You can see both the visited color link and the definition color link.

**Comment by liquid06** [comment]
This example is from a tutorial that includes these brackets as part of the link text.

**Definition box before - closed**
![dialog-closed-before](https://cloud.githubusercontent.com/assets/460005/6194345/bf1d3858-b380-11e4-8f22-9d39c1417d41.png)
**Definition box before - open**
![definition-open-before](https://cloud.githubusercontent.com/assets/460005/6194349/c41a6ec0-b380-11e4-880c-f73c3ee607d1.png)

**Definition box after - closed**
![definition-closed-after](https://cloud.githubusercontent.com/assets/460005/6194400/4ee50600-b381-11e4-8f8d-b0483f6baa2b.png)
**Definition box after - open**
![definition-open-after](https://cloud.githubusercontent.com/assets/460005/6194401/51e3b5a4-b381-11e4-8dcb-c84908bb7590.png)

**Comment by simpsonw** [comment]
Any thoughts on the new look for the definition boxes, @lsult and @yvonnemery?

**Comment by michaelhagedon** [comment]
Question: is this good enough the way it is (it's definitely better than it used to be), or should we be looking at @liquid06's other suggestion: "Adding +/- or X icons"?

**Comment by lsult** [comment]
Hey – I think it is ready to deploy – thanks everyone!

**Comment by simpsonw** [comment]
These changes are in master.  Closing issue.
