### ISSUE TITLE
The step arrows are too far from the tutorial content

### ISSUE THREAD

**Issue by michaelhagedon** [ualibraries/Guide-on-the-Side#91]
Students miss them sometimes.

**Comment by FStop** [comment]
What about something like this, with navigation at the top, instead of the bottom? 

![screen shot 2015-01-30 at 2 17 09 pm](https://cloud.githubusercontent.com/assets/1437322/5983442/b6d1f9be-a88a-11e4-879b-d16b75a2afc2.png)

I couldn't resist getting rid of some images, shadows, etc. while I was in there messing around :innocent: 

I'd love to take a crack at the theme, but maybe later...

**Comment by michaelhagedon** [comment]
That seems more likely to be noticed. Only usability testing would say for sure, but it seems like a good guess to me. Opinions, @yvonnemery , @lsult ?

**Comment by yvonnemery** [comment]
Hmm… had not thought of that. I think it looks better than at the bottom.

**Comment by lsult** [comment]
I like that it is closer, but like Yvonne, like it better under the words since they have to advance the arrow after reading?

Thanks for working on this!!

**Comment by lsult** [comment]
In case the link didn’t work.

From: Sult, Leslie A - (lsult)
Sent: Friday, January 30, 2015 3:22 PM
To: 'ualibraries/Guide-on-the-Side'; ualibraries/Guide-on-the-Side
Subject: RE: [Guide-on-the-Side] The step arrows are too far from the tutorial content (#91)

I like that it is closer, but like Yvonne, like it better under the words since they have to advance the arrow after reading?

Thanks for working on this!!

**Comment by yvonnemery** [comment]
I think we could test it with one tutorial and see what happens.

**Comment by liquid06** [comment]
Do we need to deploy branch 91-navigation-position on webdev so that @yvonnemery can do user testing for this?

**Comment by lsult** [comment]
cool - thanks! Can you send me a link that Yvonne and I can use to test? I just checked a regular GotS and the arrows are still at the bottom
I'm looking forward to hearing what students think!
________________________________

**Comment by simpsonw** [comment]
@lsult @yvonnemery The changes should be up at http://webdev.library.arizona.edu/applications/quickHelp/.  Any of the non-external tutorials (e.g. http://webdev.library.arizona.edu/applications/quickHelp/tutorial/euromonitordbforbnad) will have the arrows with the new styles.

**Comment by yvonnemery** [comment]
Will
We were going to start testing the arrows on top but realized that the text on the first screen reads "Use the arrows below..." Can you delete this sentence? We do not want to add any directions as to where the arrows are.
Yvonne
________________________________

**Comment by simpsonw** [comment]
@yvonnemery The text has been removed from (http://webdev.library.arizona.edu/applications/quickHelp/tutorial/euromonitordbforbnad).  I should mention that that text was actually in the tutorial itself, so that might pose a problem if we change the position of the arrows since other people may have had similar instructions in their tutorials.

**Comment by simpsonw** [comment]
@yvonnemery @lsult : Did you get a change to do usability testing for this?

**Comment by yvonnemery** [comment]
No. Not yet. Will hopefully next week.

**Comment by yvonnemery** [comment]
We did a little bit of usability yesterday, and for the most part students did not see the arrows and were quite confused. However, I can't say for sure it was the arrows as they mostly focused on the database and read the terms and conditions and then just stayed there without taking a look at the GOTS. When we asked them what they thought of the arrows, they said they did not see them, did not think they were for them to use, and that they looked like part of the border and did not have a function.

There is also some points in the tutorials where students logically do something and then think they need to click the next arrow because they performed a step.  It is hard to explain in words, but I can show you. This got me thinking that it would be nice to have the words " Go on" or such at the end of the text of each slide. Or even better would be to have the arrows at the end of the text. Is that possible?

**Comment by simpsonw** [comment]
@yvonnemery I think it would be feasible to move the arrows underneath the text, but the concern there is that the arrows won't be in a consistent position (i.e. they'll be farther down the page if the text is longer or higher up if the text is shorter).

Having the "Go on" text after a user completes a particular task would probably be difficult to do and prone to breaking, although I kind of like the idea from a usability standpoint.

What do you (and @lsult ) think about having a simple animated message that would fade in and draw the user's attention to the arrows the first time they do a tutorial?  Something along the lines of:
![arrow_box](https://cloud.githubusercontent.com/assets/10437788/6419490/ea50cda0-be7a-11e4-9597-efbcccaeabe4.png)

Obviously the styling needs work and we would need to add a close link/button, but that would be the general idea.

**Comment by yvonnemery** [comment]
I don't think it would be a problem to have the arrows appear in different places. As long as they are at the end of the text each time, I think it would be fine. I like that idea.
________________________________

**Comment by michaelhagedon** [comment]
@yvonnemery, what about when the text scrolls? Is it OK for the arrows to not be visible at first?

**Comment by lsult** [comment]
The problem we seem to be seeing is that people just don't notice the arrows at all - in One iteration earlier on we had back and next as part of the arrows - we never did usability so I don't know if that helped anymore but right now I think having the arrows closer to the text even if they aren't in a consistent position would be a better Q2 users to MoveOn than having the arrows way at the bottom?

Sent from my iPhone
Leslie

On Feb 27, 2015, at 12:26 PM, Michael Hagedon <notifications@github.com<mailto:notifications@github.com>> wrote:

@yvonnemery, what about when the text scrolls? Is it OK for the arrows to not be visible at first?

**Comment by lsult** [comment]
I like The fade in on the first screen idea also! I assume once they arrow wants they will know where to look that could solve the problem!!

Sent from my iPhone
Leslie

On Feb 27, 2015, at 12:23 PM, yvonnemery <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't think it would be a problem to have the arrows appear in different places. As long as they are at the end of the text each time, I think it would be fine. I like that idea.
________________________________

**Comment by lsult** [comment]
Ok one more question- is there any reason that the fade in might not play - like from a pop up blocker or would it always reliably work? I'm pretty excited about this!

Sent from my iPhone
Leslie

On Feb 27, 2015, at 12:31 PM, Sult, Leslie A - (lsult) <lsult@email.arizona.edu<mailto:lsult@email.arizona.edu>> wrote:

I like The fade in on the first screen idea also! I assume once they arrow wants they will know where to look that could solve the problem!!

Sent from my iPhone
Leslie

On Feb 27, 2015, at 12:23 PM, yvonnemery <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't think it would be a problem to have the arrows appear in different places. As long as they are at the end of the text each time, I think it would be fine. I like that idea.
________________________________

**Comment by FStop** [comment]
Good idea on the introductory tooltip, @simpsonw. Do you think we'd need a cookie to avoid annoying users who have already seen it and get the idea?

**Comment by simpsonw** [comment]
@lsult A popup blocker wouldn't affect the fade in box.  The only ways I could think of it breaking would be if either they had JavaScript completely disabled or if they had a fatal JavaScript error somewhere on the page, but in either of those circumstances a whole host of other things would be broken as well.

@FStop I think that's a really good idea, I will see if I can implement it.

I will take a shot at implementing this feature and deploy it to webdev to get more feedback.

**Comment by yvonnemery** [comment]
What I don't like about the navigation up top is that the user will be reading going down and then will have to come back up to move on. Seems cumbersome and it seems that intuitively navigation would be at the bottom.

**Comment by yvonnemery** [comment]
I am not sure about the text scrolls. We are trying to avoid putting too much text on any one slide, so I am not sure that would happen.

**Comment by simpsonw** [comment]
@yvonnemery I can see your point; people are used to seeing pagination links at the bottom of pages.  On the other hand, people are also quite used to seeing navigation items at the top of pages and windows (the forward and back buttons on a web browser being perhaps a fitting example).

I think @michaelhagedon raises an important point regarding the fact that you won't see the arrows at first if the content is long enough.  Our own internal guidelines may keep things from getting too long, but it my affect others using the open source release.

I will continue to work on implementing the fade in while I mull this over some more.

**Comment by lsult** [comment]
Hey! I think I'm confused? I guess I was assuming the fade in would go with the bottom arrows?

Sent from my iPhone
Leslie

On Feb 27, 2015, at 3:41 PM, Will Simpson <notifications@github.com<mailto:notifications@github.com>> wrote:


@yvonnemery<https://github.com/yvonnemery> I can see your point; people are used to seeing pagination links at the bottom of pages. On the other hand, people are also quite used to seeing navigation items at the top of pages and windows (the forward and back buttons on a web browser being perhaps a fitting example).

I think @michaelhagedon<https://github.com/michaelhagedon> raises an important point regarding the fact that you won't see the arrows at first if the content is long enough. Our own internal guidelines may keep things from getting too long, but it my affect others using the open source release.

I will continue to work on implementing the fade in while I mull this over some more.

**Comment by simpsonw** [comment]
@lsult We can definitely do that.  Are you thinking about having the arrows in their original position (on the bottom, but outside of the content container so they stay in one spot) or directly against the content?

**Comment by lsult** [comment]
Yay! I could go either way - if they stay as they are I am a big fan of the fade in plan. If we can't do that then I think up against the content is best?
Thanks!

Sent from my iPhone
Leslie

On Feb 27, 2015, at 4:39 PM, Will Simpson <notifications@github.com<mailto:notifications@github.com>> wrote:


@lsult<https://github.com/lsult> We can definitely do that. Are you thinking about having the arrows in their original position (on the bottom, but outside of the content container so they stay in one spot) or directly against the content?

**Comment by simpsonw** [comment]
@lsult I agree.  I think no matter where the arrows end up, the fade in message would probably be helpful.

**Comment by yvonnemery** [comment]
I think we should have a meeting to talk about the different possibilities. Leslie will make a meeting.

**Comment by simpsonw** [comment]
@yvonnemery That sounds like a good idea to me.  I will keep an eye on my inbox for a meeting request from @lsult.

**Comment by simpsonw** [comment]
Per our meeting, we are going to go with the following design:

* The arrows will be directly under the tutorial content
* They will be a slightly darker color
* If easy, we will hide the back arrow on the first slide and the forward arrow on the last slide.
* Header text should be added for the certificate and feedback sections.

**Comment by lsult** [comment]
Sweet! Thanks!

**Comment by simpsonw** [comment]
What does everyone think of the general idea here:

![gh_91_new_styles](https://cloud.githubusercontent.com/assets/10437788/6515019/1f978468-c344-11e4-8950-a43eb7a2261c.png)

**Comment by lsult** [comment]
this looks great - yay!
________________________________

**Comment by yvonnemery** [comment]
If we are not going to have status bar, then maybe make the arrows a little closer?

**Comment by yvonnemery** [comment]
I think maybe the status bar will look better with the arrows. What do others think?

**Comment by simpsonw** [comment]
@yvonnemery Are you meaning that the progress bar would move up to be directly underneath the content or that the arrows would move down to be near the progress bar?

**Comment by lsult** [comment]
I like the progress bar at the bottom and the arrows near the text the way will set it up in the
 example?
Leslie
________________________________

**Comment by yvonnemery** [comment]
Sorry. That the whole thing would move up as it was. I mean the progress bar and the arrows are all together as they have always been and they both move up to under the text. Does that make sense? Just a suggestion. Could we see a version like that? And maybe one with the arrows closer together?

**Comment by simpsonw** [comment]
@yvonnemery like this?

![screenshot from 2015-03-05 16 21 33](https://cloud.githubusercontent.com/assets/10437788/6516964/baef8f8c-c353-11e4-8798-588442875e07.png)

**Comment by yvonnemery** [comment]
Yes. I think I like that better than without the status bar. What do others think? 
________________________________________

**Comment by lsult** [comment]
i like it both ways, but the argument for having it closer is that the status bar won't get lost, but I thought that having the status bar up by the arrows would make it weird for advancing the page?
________________________________

**Comment by simpsonw** [comment]
It doesn't call any technical problems, but it does seem a bit odd to me that it scrolls off the page with the rest of the content.  What does everyone else think?

**Comment by lsult** [comment]
ok, that is what I am remembering - that it would be weird to have the bar scroll, so the choices are either figure out how to make the arrows and bar not scroll or put the bar at the bottom - right?
________________________________

**Comment by simpsonw** [comment]
That's correct, @lsult.  The thing is, as far as I can see from the way things are structured, having something close to the content and not scroll are mutually exclusive.

**Comment by lsult** [comment]
so if it is near the content it needs to scroll? (sometimes I get confused)
________________________________

**Comment by simpsonw** [comment]
That's correct.  Everything inside of the white area scrolls when you click the arrow.

**Comment by lsult** [comment]
ok, so then I think the status bar should be at the bottom - yvonne what do you think?
________________________________

**Comment by yvonnemery** [comment]
I'm not sure. I think the arrows just floating there by themselves looks kind of weird but maybe that's because I'm just not used to it. 
________________________________________

**Comment by lsult** [comment]
Yvonne - do you think it would be better to have everything scroll or do you think it would be weird to watch everything move away each time you advanced?

**Comment by simpsonw** [comment]
We could try putting the arrows close together to focus things a bit:

![snug_arrows](https://cloud.githubusercontent.com/assets/10437788/6517686/146a39b6-c35b-11e4-8989-c5fe70dfabb6.png)

**Comment by yvonnemery** [comment]
Let's try that and see what it looks like. 
________________________________________

**Comment by lsult** [comment]
I'm good with that too!

Sent from my iPhone
Leslie

On Mar 5, 2015, at 6:53 PM, yvonnemery <notifications@github.com<mailto:notifications@github.com>> wrote:

Let's try that and see what it looks like.
________________________________________

**Comment by yvonnemery** [comment]
I do like the arrows together. I still think my first choice is status bar and arrows together, but if that will look odd in the advancing, then let’s go with arrows close together.

**Comment by simpsonw** [comment]
I have deployed the changes to webdev (e.g. http://webdev.library.arizona.edu/applications/quickHelp/tutorial/searching-academic-search-complete).  Let me know what you think.  You may have to reload the page a few times or possible clear your browser cache to see all the changes.

**Comment by yvonnemery** [comment]
Looks great. I am not sure if it is my monitor but the forward arrow is grainy and the back arrow is not.

**Comment by simpsonw** [comment]
@yvonnemery I believe this is an issue with Firefox.  I will see if I can find a solution for it, but it may be outside of the scope of this task to fix.

**Comment by yvonnemery** [comment]
Let me try it on another browser. You can come see it on my monitor.

**Comment by yvonnemery** [comment]
Looks great. Let's do it and consider it done. I will be doing some more usability testing in the coming days and will provide feedback! Thank you!

**Comment by lsult** [comment]
I love it also! Thanks Will I’m excited to see what the students say when we test it!

**Comment by simpsonw** [comment]
At this point I believe this task is ready for code review.

**Comment by lsult** [comment]
Sweet! So where are we as far as rolling out the new version?

Sent from my iPhone
Leslie

On Mar 6, 2015, at 10:41 AM, Will Simpson <notifications@github.com<mailto:notifications@github.com>> wrote:


At this point I believe this task is ready for code review.

**Comment by simpsonw** [comment]
After this task passes code review, we will have to update the release notes, package and tag the release, and then I think we should be good to go.

**Comment by lsult** [comment]
How awesome! Do you need anything from me to help get it rolled out?

Sent from my iPhone
Leslie

On Mar 6, 2015, at 11:06 AM, Will Simpson <notifications@github.com<mailto:notifications@github.com>> wrote:


After this task passes code review, we will have to update the release notes, package and tag the release, and then I think we should be good to go.

**Comment by simpsonw** [comment]
Not that I can think of, but I will let you know if something occurs to me.  Thanks!

**Comment by liquid06** [comment]
I've reviewed the commits associated with this issue and they all look fine. This passes UX-Dev best practices review. I also tested out the front-end of the changes on my local copy. I'll mention my usability concerns here, but they don't need to block resolution on this issue or the next release of gots.

There's no way to get back once you're all the way at the end of the tutorial besides reloading the page or using the menu. The menu is probably not noticed most of the time and is not included if there are no chapter headings. The back button in the browser probably doesn't have the expected effect, and "back" and "reload" are not clear options when the tutorial is in popup mode. I'd recommend including the "previous" arrow on the Certificate/Feedback page.

The targets you have to hit to press those arrows are pretty small and the arrows are close together. The arrows are are one of the primary ways people need to interact with the tutorial and hopefully that's more noticeable after this update! The visual size of the arrows seems fine for drawing attention to them in balance with the content, and moving the arrows closer to the content helps a lot. But having the area to activate the link so small and the links close together might make it harder than it needs to be for a person with a motor disability to navigate. Imagine a future where gots works better on a phone - assuming those arrows were still there, distracted and one-handed, would you be able to tap the correct arrow with confidence? We have a number of other small interface elements - but they are not essential to viewing the content of the tutorial like the arrows are.

On a side note, I thought I saw a bug when the arrows followed a free response area in the demo tutorial - it wasn't a bug though, it was a bunch of empty paragraphs in the content. If tutorial creators notice that the arrows are not right next to the content, they should for extra empty "enter"s in the content, as this now affects where the arrows end up.

Speaking of the demo tutorial, we should probably remove the phrase "Use the arrows below to navigate through the tutorial" if we're planning to remove it from our content as well. I'll be glad to see it go since it makes no sense at all when a tutorial is in single-page view.

**Comment by lsult** [comment]
Thanks Ginger and thanks for doing a check of the usability

Thanks for catching that you can’t get back once you are at the end of the tutorial – Will, can we put the previous arrow on the last page and make the targets around the back and previous arrows bigger throughout? And thanks for the reminder to update the demo once the new changes are rolled out – I’ll put a note in my calendar to make sure that gets done.

As usual – thanks for an awesome collective effort – GotS would not be nearly as good without everyone’s contributions!

Leslie

**Comment by simpsonw** [comment]
I've added the "Previous" arrow to the "Certificate/Feedback" page and I also took a shot at making the arrows longer and increasing the space between them:

![larger_arrows_more_spacing](https://cloud.githubusercontent.com/assets/10437788/6741512/44949574-ce45-11e4-8c8e-188c3ac5af82.png)

Does that look good to everyone?

**Comment by lsult** [comment]
I like it - I think the arrows stand out well thanks Will!

**Comment by yvonnemery** [comment]
Me too. Looks great.

**Comment by michaelhagedon** [comment]
FYI pop-up mode arrows, progress bar, and Powered by footer are broken. I wonder if they don't use the same css?

**Comment by simpsonw** [comment]
That's weird, @michaelhagedon.  It seems to be working for me locally.
![popup_mode_arrows](https://cloud.githubusercontent.com/assets/10437788/6783659/425c0ae4-d138-11e4-97a4-995a841abf9a.png)
