### ISSUE TITLE
Make chapter progress ("Step x of y") configurable

### ISSUE THREAD

**Issue by michaelhagedon** [ualibraries/Guide-on-the-Side#93]
With shorter tutorials like UAL is now doing, the chapter progress in confusing. But make it configurable in case others still want it.

**Comment by simpsonw** [comment]
I have created a branch (gh_93_chapter_progress) for what I have so far.  I think it pretty much covers it, but I want to test it a bit more and get @michaelhagedon's opinion on the migrations-related stuff.

**Comment by simpsonw** [comment]
Looks like there are some issues with the migration for the db change, will look into it.

**Comment by simpsonw** [comment]
I believe I have fixed the db migration issues.  I deleted the branch on Github and created a new one locally and then pushed it so the old commits would not be cluttering things.  I have also committed the appropriate changes to the private UAL Subversion repo.

**Comment by michaelhagedon** [comment]
This looks good to me. If anyone (@liquid06?) wants to give feedback on the admin side microcopy, that's welcome too.  

![image](https://cloud.githubusercontent.com/assets/645924/6028406/8c0e33fe-aba6-11e4-8ccc-de8773c8f4cf.png)

**Comment by simpsonw** [comment]
If there's no objection from the team (@liquid06, @michaelhagedon, @yvonnemery, or anyone else), I will go ahead and merge this tomorrow.
